// Code generated by goctl. DO NOT EDIT.
// Source: bird.proto

package birdclient

import (
	"context"

	"github.com/iot-synergy/synergy-bird-rpc/types/bird"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BooleanResp             = bird.BooleanResp
	GalleryCreateReq        = bird.GalleryCreateReq
	GalleryListReq          = bird.GalleryListReq
	GalleryListResp         = bird.GalleryListResp
	GalleryListRespData     = bird.GalleryListRespData
	GalleryResp             = bird.GalleryResp
	GalleryRespData         = bird.GalleryRespData
	GalleryUpdateReq        = bird.GalleryUpdateReq
	IdReq                   = bird.IdReq
	IllustrationsCreateReq  = bird.IllustrationsCreateReq
	IllustrationsListReq    = bird.IllustrationsListReq
	IllustrationsListResp   = bird.IllustrationsListResp
	IllustrationsListVo     = bird.IllustrationsListVo
	IllustrationsListVoData = bird.IllustrationsListVoData
	IllustrationsResp       = bird.IllustrationsResp
	IllustrationsRespVo     = bird.IllustrationsRespVo
	IllustrationsUpdateReq  = bird.IllustrationsUpdateReq
	LabelCreateReq          = bird.LabelCreateReq
	LabelListReq            = bird.LabelListReq
	LabelListResp           = bird.LabelListResp
	LabelListVo             = bird.LabelListVo
	LabelListVoData         = bird.LabelListVoData
	LabelResp               = bird.LabelResp
	LabelUpdateReq          = bird.LabelUpdateReq
	LabelVo                 = bird.LabelVo

	Bird interface {
		GalleryCreate(ctx context.Context, in *GalleryCreateReq, opts ...grpc.CallOption) (*GalleryResp, error)
		GalleryDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*GalleryResp, error)
		GalleryList(ctx context.Context, in *GalleryListReq, opts ...grpc.CallOption) (*GalleryListResp, error)
		IllustrationCreate(ctx context.Context, in *IllustrationsCreateReq, opts ...grpc.CallOption) (*IllustrationsResp, error)
		IllustrationUpdate(ctx context.Context, in *IllustrationsUpdateReq, opts ...grpc.CallOption) (*IllustrationsResp, error)
		IllustrationList(ctx context.Context, in *IllustrationsListReq, opts ...grpc.CallOption) (*IllustrationsListResp, error)
		FindIllustrationByPage(ctx context.Context, in *IllustrationsListReq, opts ...grpc.CallOption) (*IllustrationsListVo, error)
		PublishIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IllustrationsResp, error)
		UnpublishIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IllustrationsResp, error)
		DeleteIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BooleanResp, error)
		LabelCreate(ctx context.Context, in *LabelCreateReq, opts ...grpc.CallOption) (*LabelResp, error)
		LabelUpdate(ctx context.Context, in *LabelUpdateReq, opts ...grpc.CallOption) (*LabelResp, error)
		LabelList(ctx context.Context, in *LabelListReq, opts ...grpc.CallOption) (*LabelListResp, error)
		FindLabelByPage(ctx context.Context, in *LabelListReq, opts ...grpc.CallOption) (*LabelListVo, error)
		FindLabelById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelVo, error)
		PublishLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelResp, error)
		UnpublishLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelResp, error)
		DeleteLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BooleanResp, error)
	}

	defaultBird struct {
		cli zrpc.Client
	}
)

func NewBird(cli zrpc.Client) Bird {
	return &defaultBird{
		cli: cli,
	}
}

func (m *defaultBird) GalleryCreate(ctx context.Context, in *GalleryCreateReq, opts ...grpc.CallOption) (*GalleryResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.GalleryCreate(ctx, in, opts...)
}

func (m *defaultBird) GalleryDelete(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*GalleryResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.GalleryDelete(ctx, in, opts...)
}

func (m *defaultBird) GalleryList(ctx context.Context, in *GalleryListReq, opts ...grpc.CallOption) (*GalleryListResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.GalleryList(ctx, in, opts...)
}

func (m *defaultBird) IllustrationCreate(ctx context.Context, in *IllustrationsCreateReq, opts ...grpc.CallOption) (*IllustrationsResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.IllustrationCreate(ctx, in, opts...)
}

func (m *defaultBird) IllustrationUpdate(ctx context.Context, in *IllustrationsUpdateReq, opts ...grpc.CallOption) (*IllustrationsResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.IllustrationUpdate(ctx, in, opts...)
}

func (m *defaultBird) IllustrationList(ctx context.Context, in *IllustrationsListReq, opts ...grpc.CallOption) (*IllustrationsListResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.IllustrationList(ctx, in, opts...)
}

func (m *defaultBird) FindIllustrationByPage(ctx context.Context, in *IllustrationsListReq, opts ...grpc.CallOption) (*IllustrationsListVo, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.FindIllustrationByPage(ctx, in, opts...)
}

func (m *defaultBird) PublishIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IllustrationsResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.PublishIllustration(ctx, in, opts...)
}

func (m *defaultBird) UnpublishIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IllustrationsResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.UnpublishIllustration(ctx, in, opts...)
}

func (m *defaultBird) DeleteIllustration(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BooleanResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.DeleteIllustration(ctx, in, opts...)
}

func (m *defaultBird) LabelCreate(ctx context.Context, in *LabelCreateReq, opts ...grpc.CallOption) (*LabelResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.LabelCreate(ctx, in, opts...)
}

func (m *defaultBird) LabelUpdate(ctx context.Context, in *LabelUpdateReq, opts ...grpc.CallOption) (*LabelResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.LabelUpdate(ctx, in, opts...)
}

func (m *defaultBird) LabelList(ctx context.Context, in *LabelListReq, opts ...grpc.CallOption) (*LabelListResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.LabelList(ctx, in, opts...)
}

func (m *defaultBird) FindLabelByPage(ctx context.Context, in *LabelListReq, opts ...grpc.CallOption) (*LabelListVo, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.FindLabelByPage(ctx, in, opts...)
}

func (m *defaultBird) FindLabelById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelVo, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.FindLabelById(ctx, in, opts...)
}

func (m *defaultBird) PublishLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.PublishLabel(ctx, in, opts...)
}

func (m *defaultBird) UnpublishLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*LabelResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.UnpublishLabel(ctx, in, opts...)
}

func (m *defaultBird) DeleteLabel(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*BooleanResp, error) {
	client := bird.NewBirdClient(m.cli.Conn())
	return client.DeleteLabel(ctx, in, opts...)
}
